### ISSUE TITLE
What is the difference between a Doubly Linked List and a Singly Linked List?

### ISSUE THREAD

**Issue by 3DR** [Seneca-BTP500/btp500-f16#10]
What is the difference between a Doubly Linked List and a Singly Linked List?

**Comment by HookJordan** [comment]
A doubly linked list keeps track of the next and previous item in a list. 

A singly linked list will only keep track of the next item in a linked list.

**Comment by karan-randhawa** [comment]
A doubly-linked list has nodes that contain two pointers, one to the next node and one to the previous node.
A singly-linked list will contain only one pointer, that is to the next node in the list.

A doubly-linked list allows you to traverse back on the list, whereas you can only move forward in a singly-linked list.
